### PR TITLE
[CS160-17, 22] Assignments and Courses Sidebar

### PR DESCRIPTION
**Pull request by HoaiNamPhung**
Implemented basic UI for navbar and assignments page. Navbar is fully functional (albeit the links may need to be replaced), assignments page is just the general layout with no regards to functionality/REST querying.

### CODE REVIEW

**Comment by jnguy2018** [comment]
In the tailwind.config.js file, you extended the theme to include custom colors, did you end up using those colors?

**Review by jnguy2018 — APPROVED** [review]
In your tailwind.config.js file, you extended the colors to include custom colors I think. Did you end up using them in your project?

**Comment by HoaiNamPhung** [comment]
> 
> 
> In your tailwind.config.js file, you extended the colors to include custom colors I think. Did you end up using them in your project?

Nope; couldn't get the colors to work. For now I'm just using base tailwind colors.

**Review by shahadeshubhu — APPROVED** [review]
Looking good. I feel there's no issues in it

**Pull request merged**
